version: "3.8"

services:
  sqlserver:
    build: ./backend/5s_backend/5sDB
    volumes:
      - data:/var/opt/mssql
    ports:
      - "1435:1433"
    env_file:
      - ./env/sqlserver.env
    networks:
      - five-s
    container_name: five-sdb
  backend:
    build: ./backend/5s_backend/5s
    ports:
      - "7124:7124"
    networks:
      - five-s
    depends_on:
      - sqlserver
    container_name: five-sbackend
  frontend:
    build: ./frontend/5splus1-f1-07
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/5splus1-f1-07/src:/app/src
    depends_on:
      - backend
    networks:
      - five-s
    container_name: five-sfrontend

networks:
  five-s:

volumes:
  data:
